name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "rag-agent"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"


      # Paso 3: Cargar las variables de entorno necesarias
      - name: Set environment variables
        run: |
          echo "MONGODB_URI_AGENT=${{ secrets.MONGODB_URI_AGENT }}" >> $GITHUB_ENV

      # Paso 4: Crear el archivo .env (opcional pero recomendado)
      - name: Create .env file
        run: |
          echo "MONGODB_URI_AGENT=${{ secrets.MONGODB_URI_AGENT }}" > .env

      - name: npm install, build
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./build/standalone