name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "rag-agent"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - uses: actions/checkout@v4

      # Configurar la versión de Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Cargar la variable de entorno en el entorno de ejecución de Actions
      - name: Set environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      # Crear el archivo .env para Next.js (opcional)
      - name: Create .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env

      # Instalar dependencias y construir la aplicación
      - name: Install and build
        run: |
          npm install
          npm run build
          # Verificar y mover la carpeta static si existe
          if [ -d "./build/static" ]; then
            mkdir -p ./build/standalone/.next
            mv ./build/static ./build/standalone/.next/static
          fi
          # Verificar y mover la carpeta public si existe
          if [ -d "./public" ]; then
            mkdir -p ./build/standalone/public
            mv ./public ./build/standalone/public
          fi

      # Desplegar la aplicación a Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./build/standalone
